  name: AdvancedHomes
  main: de.aaron.advancedhomes.main.AdvancedHomes
  Author: Veroxar
  description: Advanced Homes entwickelt von Veroxar!
  version: 1.0

  commands:
    adho:
      description: Command Prefix von Advanced Homes!
      usage: /adho help
    sethome:
      description: Setze dein Home!
      usage: /sethome [Name]
    delhome:
      description: Löscht dein Home!
      usage: /delhome [Name]
    homes:
      description: Zeigt dir deine Homes an!
      usage: /homes
    home:
      description: Teleportiert dich zu deinem Home!
      usage: /home [name]

